baseURL = "https://openschools.netlify.com/"
languageCode = "en-us"
title = "Open Source Schools"
theme = "KeepIt"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Welcome"
    url  = "/welcome"
    weight = 2
[[menu.main]]
    name = "Posts"
    url  = "/posts"
    weight = 3
[[menu.main]]
    name = "Admin"
    url  = "/admin"
    weight = 5
[[menu.main]]
    name = "Get Involved"
    url  = "/get-involved"
    weight = 4
