baseURL = "http://upbeat-lewin-f7503d.netlify.com/"
languageCode = "en-us"
title = "Open Source Schools"
theme = "KeepIt"

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Welcome"
    url  = "/#welcome"
    weight = 2
[[menu.main]]
    name = "Blog Posts"
    url  = "/#blog-posts"
    weight = 3
[[menu.main]]
    name = "Admin"
    url  = "/admin"
    weight = 4
